name: SPS Backend CI

on: 
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  ROCKET_DATABASES: "{ sps_mysql = { url = mysql://root:root@localhost/ApolloniusTesting } }"
  DATABASE_URL: mysql://root:root@localhost/ApolloniusTesting

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start Test Mysql server
        run: sudo /etc/init.d/mysql start

      - name: Create Test DB
        run: mysql -uroot -proot < ./sql/test_db_setup.sql

      - name: Install Rust Toolchain - Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run Cargo tests
        run: cargo test --verbose

      - name: Reset Test DB
        run: mysql -uroot -proot < ./sql/test_db_setup.sql

      - name: Installing Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: Run Tarpaulin
        run: cargo tarpaulin --all-features --workspace --timeout 120 --out Xml

      - name: Upload to Code Cov
        uses: codecov/codecov-action@v3.1.1
        with:
          fail_ci_if_error: true

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust Toolchain - Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Start Test Mysql server
        run: sudo /etc/init.d/mysql start

      - name: Create Test DB
        run: mysql -uroot -proot < ./sql/test_db_setup.sql

      - name: Build
        run: cargo build --verbose
