name: SPS Backend CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always
  ROCKET_DATABASES: ${{ secrets.DB_URL }}
  DATABASE_URL: ${{ secrets.SQLX_DB_URL }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust Toolchain - Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Run Tests
        run: cargo test --verbose

      - name: Run Tarpaulin
        uses: actions-rs/tarpaulin@v0.1

      - name: Upload to Code Cov
        uses: codecov/codecov-action@v3.1.1
        with:
          fail_ci_if_error: true

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust Toolchain - Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --verbose
