name: Rust

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ROCKET_DATABASES: ${{ secrets.DB_URL }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - uses: Swatinem/rust-cache@v2 
    - name: Run tests
      run: cargo test --verbose
